# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d416c8927b83fa68c5e69792d210240ae7fa838a1b56b54768acc862f73dd6da84f4a23febdef7d109bb24d58475e6e311733abcf4f15fe97cb332f556f2f4da

test:
  secret_key_base: d0688df1703dad413c600e0df2285c32efa4f219d69d4bf2371dd347aab890db7534c0cf30a120e411c656c4600d4cbe2d4c02c4cca766c33b4130cfa22814f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
